//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apisBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVOENTRADA
    {
        public int IdArchivoEntrada { get; set; }
        public int IdEntrada { get; set; }
        public string Path { get; set; }
    
        public virtual ENTRADA ENTRADA { get; set; }
    }
}
