//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apisBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORENTRADA
    {
        public int IdAutorEntrada { get; set; }
        public int IdEntrada { get; set; }
        public int Carnet { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual ENTRADA ENTRADA { get; set; }
    }
}
