//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apisBlog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    
    public partial class XTecTutorDBEntities : DbContext
    {
        public XTecTutorDBEntities()
            : base("name=XTecTutorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<ARCHIVOENTRADA> ARCHIVOENTRADAs { get; set; }
        public virtual DbSet<AUTORENTRADA> AUTORENTRADAs { get; set; }
        public virtual DbSet<CALIFICACIONENTRADA> CALIFICACIONENTRADAs { get; set; }
        public virtual DbSet<CARRERA> CARRERAs { get; set; }
        public virtual DbSet<COMENTARIOENTRADA> COMENTARIOENTRADAs { get; set; }
        public virtual DbSet<CURSO> CURSOes { get; set; }
        public virtual DbSet<ENTRADA> ENTRADAs { get; set; }
        public virtual DbSet<ESTUDIANTE> ESTUDIANTEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEMA> TEMAs { get; set; }

    }
}
